$color = rgba(59, 47, 49, 1)         
$inner_color = rgba(59, 47, 49, 0.66)
$outer_color = rgba(127, 166, 143, 1) 
$font_color = rgba(234, 221, 221, 1)  
$placeholder_color = rgba(234, 221, 221, 0.6)
$check_color = rgba(121, 166, 163, 1) 