

# ████████╗███████╗██████╗ ██████╗  █████╗ ███╗   ███╗ ██████╗ ██╗   ██╗██████╗ 
# ╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗ ████║██╔═══██╗██║   ██║██╔══██╗
#    ██║   █████╗  ██████╔╝██████╔╝███████║██╔████╔██║██║   ██║██║   ██║██████╔╝
#    ██║   ██╔══╝  ██╔══██╗██╔══██╗██╔══██║██║╚██╔╝██║██║   ██║██║   ██║██╔══██╗
#    ██║   ███████╗██║  ██║██║  ██║██║  ██║██║ ╚═╝ ██║╚██████╔╝╚██████╔╝██║  ██║
#    ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝
                                                                              

# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(7fa68f)
$inactiveBorderColor = rgb(8f7f80)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
