# ─────────────────────────────
# Kitty Theme — Terramour
# Cozy • Clean • Moody
# ─────────────────────────────

background            #3b2f31
foreground            #eadddd
cursor                #eadddd
selection_background  #b8a9a9
selection_foreground  #3b2f31

# Normal colors
color0   #3b2f31
color1   #d07a7a
color2   #7fa68f
color3   #d6c37a
color4   #8fa3d1
color5   #b08fd1
color6   #79a6a3
color7   #eadddd

# Bright colors
color8   #9c8c8d
color9   #dc8888
color10  #8fb298
color11  #e1cf8a
color12  #9fb3df
color13  #bc9cde
color14  #88b3b0
color15  #ffffff

# Borders
active_border_color     #eadddd
inactive_border_color   #443739
bell_border_color       #d07a7a